---
#
# edX Configuration
#
# github:     https://github.com/openedx/configuration
# wiki:       https://openedx.atlassian.net/wiki/display/OpenOPS
# code style: https://openedx.atlassian.net/wiki/display/OpenOPS/Ansible+Code+Conventions
# license:    https://github.com/openedx/configuration/blob/master/LICENSE.TXT
#
#
#
# Tasks for role redis
#
# Overview:
#
#
# Dependencies:
#
#
# Example play:
#
#

- name: Ensure dependencies are installed.
  ansible.builtin.apt:
    name:
      - gnupg2
    state: present
    update_cache: true

- name: Add the redis repo signing key
  ansible.builtin.apt_key:
    url: https://packages.redis.io/gpg
    state: present
  retries: 3
  tags:
    - install
    - install:app-requirements

- name: Add the redis repo to the sources list
  ansible.builtin.apt_repository:
    repo: "{{ REDIS_REPO }}"
    state: present
  tags:
    - install
    - install:app-requirements

- name: Install redis packages
  ansible.builtin.apt:
    name: "{{ redis_debian_pkgs }}"
    install_recommends: true
    state: present
    update_cache: true
  notify:
    - Reload redis

- name: Pin redis package version
  loop: "{{ redis_debian_pkgs }}"
  ansible.builtin.dpkg_selections:
    # Dpkg selection just wants the package name, not the package and version
    # This turns "redis=6:6.2.6-3rl1~focal1" into just "redis"
    name: "{{ item.split('=')[0] }}"
    selection: hold

- name: Update redis configuration
  ansible.builtin.template:
    src: etc/redis/redis.conf.j2
    dest: /etc/redis/redis.conf
    owner: root
    group: "{{ redis_group }}"
    mode: "0640"
  notify:
    - Reload redis
