---
- name: Clean the backup root path before starting the routine
  ansible.builtin.file:
    state: absent
    path: "{{ mysql_artifact_path }}/"
  when: |
    MYSQL_BACKUP_PRE_CLEAN_ROOT
    and mysql_artifact_path is defined
    and mysql_artifact_path != ""
    and MYSQL_BACKUP_STORAGE_OPTIONS.EXTERNAL_STORAGE_TYPE != ""

- name: Ignore PEP 668
  ansible.builtin.file:
    path: /usr/lib/python3.12/EXTERNALLY-MANAGED
    state: absent
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version is version('24', '>=')

- name: Launch MySQL Backups
  ansible.builtin.include_tasks: backup.yml
- name: Clean artifact path
  ansible.builtin.file:
    state: absent
    path: "{{ mysql_artifact_path }}/"
  when: mysql_artifact_path is defined and mysql_artifact_path != "" and MYSQL_BACKUP_STORAGE_OPTIONS.EXTERNAL_STORAGE_TYPE != ""
