---
- name: Adding extra MySQL users
  mysql_user:
    name: "{{ item.name }}"
    host: "{{ item.host | default(MYSQL_CONFIG_DEFAULT_ALLOWED_HOSTS) }}"
    password: "{{ item.password }}"
    priv: "{{ item.priv }}"
    state: "{{ item.state | default('present') }}"
    append_privs: "{{ item.append_privs | default('no') }}"
    encrypted: "{{ item.encrypted | default('no') }}"
  when: item.name != None and item.name != ''
  with_items: "{{ MYSQL_CONFIG_USERS }}"
