# Default values for ansible-runner.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: ednxops/atlas-ansible-utils
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

nameOverride: ""
fullnameOverride: ""
imagePullSecrets: []

sshSecret:
  key: ''

checkoutDirs: |
  ansible_inventory

gitSync:
  registry: registry.k8s.io
  image: defaultbackend-amd64
  tag: "v4.5"
  runAsNonRoot: true
  oneTime: true
  maxFailures: 3
  revision: main
  repository: git@github.com/eduNEXT/fake-inventory.git
  root: /git
  link: /git/manifest
  depth: 1
  ssh: true
  sshKeyFile: "/git/ssh"
  sshKnownHosts: false
  extraEnvs: []

podAnnotations: {}
podLabels: {}

podSecurityContext:
  fsGroup: 1000

jobs:
  - playbook: test_os_info
    # extraEnvs:
    #   - name: ATLAS_ANSIBLE_PLAYBOOK_EXTRA_PARAMS
    #     value: -vvv
    # successfulJobsHistoryLimit: 2
    # failedJobsHistoryLimit: 2
    # startingDeadlineSeconds: 300
    # # -- Extra Volumes for the pod
    # extraVolumes: #[]
    #   - name: example
    #     configMap:
    #       name: example
    #
    # # -- Extra Volume Mounts for the container
    # extraVolumeMounts: #[]
    #   - name: example
    #     mountPath: /example


nodeSelector: {}

tolerations: []

affinity: {}
