---
# handlers file for caddy
- name: Restart caddy
  ansible.builtin.service:
    name: caddy
    state: restarted
- name: Reload caddy
  ansible.builtin.service:
    name: caddy
    state: reloaded
