---
- name: Format Caddyfile
  ansible.builtin.shell: |
    set -o pipefail
    cat /etc/caddy/base | caddy fmt - > /etc/caddy/Caddyfile

- name: Reload caddy
  ansible.builtin.service:
    name: caddy
    state: reloaded
