---
- name: Format Caddyfile
  ansible.builtin.shell:
    cmd: set -o pipefail && cat /etc/caddy/base | caddy fmt - > /etc/caddy/Caddyfile
    executable: /bin/bash

- name: Reload caddy
  ansible.builtin.service:
    name: caddy
    state: reloaded
