---
- name: Restart native ClickHouse server
  listen: Restart ClickHouse for backup disk
  ansible.builtin.service:
    name: clickhouse-server
    state: restarted
  when:
    - CLICKHOUSE_BACKUP_RESTART_ON_CONFIG_CHANGE | bool
    - not clickhouse_backup_use_docker | bool

- name: Recreate ClickHouse docker container
  listen: Restart ClickHouse for backup disk
  ansible.builtin.command:
    argv:
      - docker
      - compose
      - -f
      - "{{ clickhouse_backup_compose_file }}"
      - up
      - -d
      - --force-recreate
      - --remove-orphans
  when:
    - CLICKHOUSE_BACKUP_RESTART_ON_CONFIG_CHANGE | bool
    - clickhouse_backup_use_docker | bool
  changed_when: false
