---
skip_list:
  - var-naming
  - no-changed-when
  - no-handler

kinds:
  - yaml: "**/*.yaml"

exclude_paths:
  - molecule
  - .github/
  - catalog-info.yaml

warn_list:
  - yaml[line-length]
  - jinja
