---
# Description: Playbook to clone Mongo databases by extracting backups and restore them with
# changed database names in the same Mongo instance.
- name: Launch Mongo backup and restore
  hosts: mongo_servers
  become: true
  gather_facts: true
  roles:
    - role: mongo_clone
      tags:
        - mongo_clone
