---
# Description: Playbook to launch MySQL backups
- name: Launch MySQL backups
  hosts: mysql_servers
  become: true
  gather_facts: true
  roles:
    - role: mysql_backup
      tags:
        - mysql_backup
