---
# Description: Playbook to clone MySQL databases by extracting backups and restore them with
# changed database names in the same MySQL instance.
- name: Launch MySQL backup and restore
  hosts: mysql_servers
  become: true
  gather_facts: true
  roles:
    - role: mysql_clone
      tags:
        - mysql_clone
