[semantic_release]
commit_message = "chore(release): preparing {version}"

[semantic_release.branches.main]
match = "(main|master)"
prerelease_token = "rc"
prerelease = false

[semantic_release.changelog]
template_dir = "changelog_templates"
changelog_file = "CHANGELOG.md"
exclude_commit_patterns = [
  "docs",
  "build",
  "style",
  "chore",
  "ci",
  "test",
]

[semantic_release.commit_author]
env = "GIT_COMMIT_AUTHOR"
default = "semantic-release <semantic-release>"
