# This playbook is ONLY used for testing purposes.
# It helps to verify ansible-playbook binary is able to run playbooks as expected.
- hosts: localhost
  gather_facts: yes
  become: false
  tasks:
  - name: Printing system details for testing purposes
    debug: msg="{{ item }}"
    loop:
    - "{{ ansible_distribution }}"
    - "{{ ansible_distribution_version }}"
    - "{{ ansible_distribution_major_version }}"
