---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Verify Redis installation
    register: redis-cli
    shell: |
      redis-cli --raw incr ping
