---
# defaults file for caddy

# Packages
caddy_package: caddy
caddy_package_state: present

# Debian
caddy_apt_repository: deb https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main
caddy_apt_gpg_key: https://dl.cloudsmith.io/public/caddy/stable/gpg.key

# Caddy options
caddy_sites: []
caddy_extra_rules: |
  # Additional directives to include, for example:
  #
  # example2.com {
  #   reverse_proxy localhost:9000
  # }

# Set the backend servers targets for reverse proxy in the format specified in
# https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#to
caddy_backend_target:
  - localhost:8080
# To configure this variable, please refer to
# https://caddyserver.com/docs/caddyfile/options
caddy_global_options:
