---
# defaults file for caddy

# Packages
caddy_package: caddy
caddy_package_state: present

# Service options
caddy_restart_handler_state: restarted

# Debian
caddy_apt_repository: deb https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main
caddy_apt_gpg_key: https://dl.cloudsmith.io/public/caddy/stable/gpg.key

# Caddy options
caddy_sites: []
caddy_extra_options: null  
caddy_backend_target: "localhost:8080" # expected an value for reverse proxy https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#to
caddy_global_options: null # To configure this variable, please refer to https://caddyserver.com/docs/caddyfile/options
