---
# defaults file for caddy

# Packages
caddy_package: caddy
caddy_package_state: present

# Service options
caddy_restart_handler_state: restarted

# Debian
caddy_apt_repository: deb https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version main
caddy_apt_gpg_key: https://dl.cloudsmith.io/public/caddy/stable/gpg.key

# Caddy options
caddy_extra_options: |
  :2015
  respond "Hello, world!"
