{{- if and (eq .Values.connection.type "ssm") (not .Values.aws.existingSecret) .Values.awsSecret.accessKeyId .Values.awsSecret.secretAccessKey }}
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: {{ include "ansible-runner.namespace" . }}
type: Opaque
stringData:
  {{ .Values.aws.accessKeyIdKey }}: {{ .Values.awsSecret.accessKeyId | quote }}
  {{ .Values.aws.secretAccessKeyKey }}: {{ .Values.awsSecret.secretAccessKey | quote }}
{{- end }}
