{{- range $.Values.jobs }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: "{{ include "ansible-runner.fullname" $ }}-{{ .playbook | replace "_" "-"}}"
  namespace: {{ include "ansible-runner.namespace" $ }}
  labels:
    {{- include "ansible-runner.labels" $ | nindent 4 }}
spec:
  schedule: {{ .schedule | default "@yearly" | quote  }}
  successfulJobsHistoryLimit: {{ .successfulJobsHistoryLimit | default 1 }}
  failedJobsHistoryLimit: {{ .failedJobsHistoryLimit | default 1 }}
  startingDeadlineSeconds: {{ .startingDeadlineSeconds | default 900 }}
  suspend: true
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          containers:
            - image: "{{ $.Values.image.repository }}:{{ default (include "ansible-runner.defaultTag" $) $.Values.image.tag }}"
              imagePullPolicy: {{ $.Values.image.pullPolicy }}
              {{- if $.Values.imagePullSecrets }}
              imagePullSecrets: {{ toYaml $.Values.imagePullSecrets | nindent 14 }}
              {{- end }}
              name: ansible-runner
              env:
                - name: ANSIBLE_PRIVATE_KEY_FILE
                  value: /git/ssh
                - name: ATLAS_ANSIBLE_PLAYBOOK
                  value: {{ printf "%s.yml" .playbook }}
                - name: ANSIBLE_INVENTORY
                  value: /git/manifests/ansible_inventory/hosts.ini
                  {{- if .extraEnvs }}
                    {{- toYaml .extraEnvs | nindent 16}}
                  {{- end }}
              volumeMounts:
                - mountPath: /git
                  name: inventory-content
                - mountPath: /git/ssh
                  name: ssh-key
                  subPath: ssh-privatekey
                  readOnly: true
          initContainers:
            - image: registry.k8s.io/git-sync/git-sync:v4.0.0
              name: inventory-git-sync
              env:
                - name: GITSYNC_ROOT
                  value: /git
                - name: GITSYNC_LINK
                  value: /git/manifests
                - name: GITSYNC_SPARSE_CHECKOUT_FILE
                  value: /sparse-checkout-file
                - name: GITSYNC_SSH_KEY_FILE
                  value: /ssh-key
                - name: GITSYNC_DEPTH
                  value: {{ $.Values.gitSync.depth | quote}}
                - name: GITSYNC_MAX_FAILURES
                  value: {{ $.Values.gitSync.maxFailures | quote}}
                - name: GITSYNC_ONE_TIME
                  value: {{ $.Values.gitSync.oneTime | quote}}
                - name: GITSYNC_REF
                  value: {{ $.Values.gitSync.revision | quote}}
                - name: GITSYNC_REPO
                  value: {{ $.Values.gitSync.repository | quote}}
                - name: GITSYNC_SSH
                  value: {{ $.Values.gitSync.ssh | quote}}
                - name: GITSYNC_SSH_KNOWN_HOSTS
                  value: {{ $.Values.gitSync.sshKnownHosts | quote}}
              volumeMounts:
                - mountPath: /git
                  name: inventory-content
                - mountPath: /sparse-checkout-file
                  name: sparse-checkout-file
                  subPath: sparse-checkout
                  readOnly: true
                - mountPath: /ssh-key
                  name: ssh-key
                  subPath: ssh-privatekey
                  readOnly: true
          restartPolicy: Never
          {{- with $.Values.podSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumes:
          - name: inventory-content
            emptyDir: {}
          - name: sparse-checkout-file
            configMap:
              name: sparse-checkout-file
          - name: ssh-key
            secret:
              secretName: ssh-key
{{- end }}
