apiVersion: v1
kind: Secret
metadata:
  name: ssh-key
  namespace: {{ include "ansible-runner.namespace" . }}
type: kubernetes.io/ssh-auth
data:
  {{- with .Values.sshSecret.key }}
  ssh-privatekey: {{ . | b64enc | quote }}
  {{- end }}
