apiVersion: v1
kind: Secret
metadata:
  name: ssh-key
  namespace: {{ include "ansible-runner.namespace" . }}
type: kubernetes.io/ssh-auth
data:
  {{- with .Values.sshSecret.key }}
  ssh-privatekey: {{ . | b64enc | quote }}
  {{- end }}
{{- if and (eq .Values.connection.type "ssm") (not .Values.aws.existingSecret) .Values.awsSecret.accessKeyId .Values.awsSecret.secretAccessKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: {{ include "ansible-runner.namespace" . }}
type: Opaque
stringData:
  {{ .Values.aws.accessKeyIdKey }}: {{ .Values.awsSecret.accessKeyId | quote }}
  {{ .Values.aws.secretAccessKeyKey }}: {{ .Values.awsSecret.secretAccessKey | quote }}
{{- end }}
