---
- name: Ensure dependencies are installed.
  ansible.builtin.apt:
    name:
      - debian-keyring
      - debian-archive-keyring
      - apt-transport-https
      - gnupg2
      - curl
    state: present
    update_cache: true

- name: Add Caddy apt key.
  ansible.builtin.get_url:
    url: "{{ caddy_apt_gpg_key }}"
    dest: /etc/apt/trusted.gpg.d/caddy.asc
    mode: "0644"
    force: true

- name: Add Caddy repository.
  ansible.builtin.apt_repository:
    repo: "{{ caddy_apt_repository }}"
    state: present
    update_cache: true

- name: Install Caddy
  ansible.builtin.package:
    name: "{{  caddy_package }}"
    state: "{{ caddy_package_state }}"

- name: Copy Caddyfile
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: /etc/caddy/Caddyfile
  tags:
    - molecule-idempotence-notest

- name: Format Caddyfile
  ansible.builtin.command: caddy fmt /etc/caddy/Caddyfile --overwrite
  notify: reload caddy
  tags:
    - molecule-idempotence-notest
