---

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Verify ElasticSearch installation
    uri:
      url: http://localhost:9200/
      status_code: 200
      timeout: 1
      return_content: yes
