---
- name: Clean the backup root path before starting the routine
  ansible.builtin.file:
    state: absent
    path: "{{ mongo_artifact_path }}/"
  when: |
    MONGO_BACKUP_PRE_CLEAN_ROOT
    and mongo_artifact_path is defined
    and mongo_artifact_path != ""
    and MONGO_BACKUP_STORAGE_OPTIONS.EXTERNAL_STORAGE_TYPE != ""

- name: Launch Mongo Backups
  ansible.builtin.include_tasks: backup.yml
- name: Clean artifact path
  ansible.builtin.file:
    state: absent
    path: "{{ mongo_artifact_path }}/"
  when: mongo_artifact_path is defined and mongo_artifact_path != ""and MONGO_BACKUP_STORAGE_OPTIONS.EXTERNAL_STORAGE_TYPE != ""
