- name: Clean the backup root path before starting the routine
  file:
    state: absent
    path: "{{ mongo_artifact_path }}/"
  when: MONGO_BACKUP_PRE_CLEAN_ROOT and mongo_artifact_path is defined and mongo_artifact_path != "" and
        MONGO_BACKUP_STORAGE_OPTIONS.EXTERNAL_STORAGE_TYPE != ""

- name: Launch Mongo Backups
  include_tasks: backup.yml

- name: Clean artifact path
  file:
    state: absent
    path: "{{ mongo_artifact_path }}/"
  when: mysql_artifact_path is defined and mysql_artifact_path != "" and
        MYSQL_BACKUP_STORAGE_OPTIONS.EXTERNAL_STORAGE_TYPE != "" and
        not MONGO_RESTORE_BACKUP | bool