# Description: Playbook to launch Mongo backups
# It is compatible with the S3 API for storage.
---

- name: Clean the backup root path before starting the routine
  file:
    state: absent
    path: "{{ mongo_artifact_path }}/"
  when: MONGO_BACKUP_PRE_CLEAN_ROOT and mongo_artifact_path is defined and mongo_artifact_path != "" and
        MONGO_BACKUP_STORAGE_OPTIONS.EXTERNAL_STORAGE_TYPE != ""

- name: Create backup directory
  file:
    path: "{{ MONGO_BACKUP_LOCATION }}"
    state: directory

- name: Create mongo database backup
  shell: >
    mongodump
    --authenticationDatabase admin
    -u {{ MONGO_BACKUP_USER }} -p '{{ MONGO_BACKUP_PASSWORD }}'
    --gzip
    --archive={{ MONGO_BACKUP_LOCATION }}/{{ MONGO_BACKUP_DATE }}.mongo

- name: Give the server time to recover
  pause:
    minutes: 1
    prompt: Pausing to give the server time to recover

- name: Execute the storage of the backup
  include_role:
    name: storage_backups
  vars:
    STORAGE_BACKUPS_OPTIONS: "{{ MONGO_BACKUP_STORAGE_OPTIONS }}"
    STORAGE_BACKUPS_FILES_TO_UPLOAD:
      - "{{ MONGO_BACKUP_LOCATION }}/{{ MONGO_BACKUP_DATE }}.mongo"
    STORAGE_BACKUPS_FOLDER: "mongo"

- name: Clean artifact path
  file:
    state: absent
    path: "{{ mongo_artifact_path }}/"
  when: mongo_artifact_path is defined and mongo_artifact_path != "" and
        MONGO_BACKUP_STORAGE_OPTIONS.EXTERNAL_STORAGE_TYPE != ""
