---
- name: Clean the backup root path before starting the routine
  ansible.builtin.file:
    state: absent
    path: "{{ mongo_artifact_path }}/"
  when: |
    MONGO_BACKUP_PRE_CLEAN_ROOT
    and mongo_artifact_path is defined
    and mongo_artifact_path != ""
    and MONGO_BACKUP_STORAGE_OPTIONS.EXTERNAL_STORAGE_TYPE != ""

# Since ubuntu 24 has problems with the backup playbook because of PEP 668 when updating the libraries, we proceed
# to create a task to ignore EXTERNALLY-MANAGED
- name: Get python system info
  community.general.python_requirements_info:
  register: python_info

- name: Ignore PEP 668 (Ubuntu/Debian)
  ansible.builtin.file:
    path: "/usr/lib/python{{ python_info.python_version | regex_replace('^(\\d+\\.\\d+).*', '\\1') }}/EXTERNALLY-MANAGED"
    state: absent
  when:
    # Condition for Ubuntu 24.04+ or Debian 12+
    - (ansible_distribution == 'Ubuntu' and ansible_distribution_version is version('24', '>=')) or
      (ansible_distribution == 'Debian' and ansible_distribution_major_version | int >= 12)

- name: Launch Mongo Backups
  ansible.builtin.include_tasks: backup.yml
- name: Clean artifact path
  ansible.builtin.file:
    state: absent
    path: "{{ mongo_artifact_path }}/"
  when: mongo_artifact_path is defined and mongo_artifact_path != ""and MONGO_BACKUP_STORAGE_OPTIONS.EXTERNAL_STORAGE_TYPE != ""
