- name: Upload the backup to a remote storage
  include_role:
    name: available_storage
  vars:
    DISK_TO_CHECK: "{{ MONGO_VOLUMES[0].device }}"

- name: Launch MongoDB backup
  include_role:
    name: mongo_backup
  vars:
    MONGO_RESTORE_BACKUP: True
    MONGO_BACKUP_ALL_DATABASES: false
    MONGO_BACKUP_DATABASES: "{{ MONGO_RESTORE_DATABASE }}"
    MONGO_BACKUP_PASSWORD: "{{ MONGO_RESTORE_PASSWORD }}"
    MONGO_BACKUP_DATABASES: "{{ MONGO_RESTORE_DATABASE }}"
    MONGO_BACKUP_ROOT: "{{ MONGO_RESTORE_BACKUP_ROOT }}"
    MONGO_BACKUP_DATE: "{{ MONGO_RESTORE_BACKUP_DATE }}"
    MONGO_BACKUP_LOCATION: "{{ MONGO_RESTORE_BACKUP_LOCATION }}"

- name: Launch restore MongoDB Backup
  include_tasks: restore.yml
  vars:
    MONGO_BACKUP_FILE: "{{ MONGO_RESTORE_BACKUP_LOCATION }}/{{ MONGO_RESTORE_BACKUP_DATE }}.gz"

- name: Clean artifact path
  include_role:
    name: clean_path
  vars:
    CLEAN_PATH: "{{ MONGO_RESTORE_BACKUP_ROOT }}"
