- name: Launch Mongo check available storage
  include_role:
    name: available_storage
  vars:
    AVAILABLE_STORAGE_DISK_TO_CHECK: "{{ MONGO_VOLUMES[0].device }}"

- name: Launch restore MongoDB Backup
  include_tasks: restore.yml
  vars:
    MONGO_BACKUP_FILE: "{{ MONGO_RESTORE_BACKUP_LOCATION }}/{{ MONGO_RESTORE_BACKUP_DATE }}_mongo.gz"

- name: Clean artifact path
  file:
    state: absent
    path: "{{ MONGO_RESTORE_BACKUP_ROOT }}"
