- name: Restore database
  shell: >
    mongorestore
    --authenticationDatabase admin
    -u {{ MONGO_RESTORE_USER  }} -p '{{ MONGO_RESTORE_PASSWORD }}'
    --gzip
    --archive={{ MONGO_BACKUP_FILE }}
    --numParallelCollections={{ MONGO_RESTORE_NUM_PARALLEL_COLLECTIONS }}
    {% if MYSQL_RESTORE_DATABASE %}
    --nsFrom={{ MONGO_RESTORE_DATABASE }}.*
    --nsTo={{ MONGO_RESTORE_CLONE_DATABASE }}.*
    {% endif %}
