---
- name: Update mysql configuration
  ansible.builtin.template:
    src: mysqld.cnf.j2
    dest: "{{ MYSQL_CONFIG_EXTRA_CONFIG_PATH }}/mysqld.cnf"
    mode: preserve
  notify:
    - Restart mysql

- name: Put replication configuration file
  ansible.builtin.template:
    src: replication.cnf.j2
    dest: "{{ MYSQL_CONFIG_EXTRA_CONFIG_PATH }}/replication.cnf"
    mode: preserve
  notify:
    - Restart mysql

- name: Creating MySQL systemd custom dir
  ansible.builtin.file:
    path: /etc/systemd/system/mysql.service.d
    state: directory
    mode: "0755"

- name: Update mysql systemd configuration
  ansible.builtin.template:
    src: override.conf.j2
    dest: /etc/systemd/system/mysql.service.d/override.conf
    mode: preserve
  notify:
    - Restart mysql

- name: Configure encryption at rest with component_keyring_file
  ansible.builtin.include_tasks: encrypt_component_keyring_file.yml
  when:
    - MYSQL_CONFIG_ENCRYPTION_ENABLED
    - MYSQL_CONFIG_KEYRING_COMPONENT == 'component_keyring_file'

# Render the encryption config file when disabling encryption
- name: Put encryption configuration file (encryption disabled)
  ansible.builtin.template:
    src: encryption.cnf.j2
    dest: "{{ MYSQL_CONFIG_EXTRA_CONFIG_PATH }}/encryption.cnf"
    mode: preserve
  when: not MYSQL_CONFIG_ENCRYPTION_ENABLED
  notify:
    - Restart mysql
