- name: Check current encryption state of mysql tablespace
  ansible.builtin.shell: |
    mysql -e "
      SELECT COALESCE(
        (SELECT ENCRYPTION
           FROM INFORMATION_SCHEMA.INNODB_TABLESPACES
          WHERE NAME='mysql' LIMIT 1),
        'N'
      ) AS enc;
    "
  register: mysql_ts_enc
  changed_when: false  # This task does not change the system state

- name: Encrypt mysql system tablespace if needed
  ansible.builtin.shell: |
    mysql -e "
      ALTER TABLESPACE mysql ENCRYPTION='Y';
    "
  when: mysql_ts_enc.stdout.find('N') != -1
