---
- name: Fail if trying to install on an unsupported distribution
  fail:
    msg: MySQL must be installed in a supported distribution
  when: ansible_distribution_release not in MYSQL_8_4_SUPPORTED_DISTRIBUTIONS

- name: Install mysql dependencies
  apt:
    name: "{{ mysql_8_4_debian_pkgs }}"
    install_recommends: yes
    update_cache: yes
    state: present

- name: Add MySQL repository key
  apt_key:
    keyserver: "{{ MYSQL_8_4_APT_KEYSERVER }}"
    id: "{{ MYSQL_8_4_APT_KEY }}"
    state: present

- name: Update APT cache
  apt:
    update_cache: yes

- name: Add MySQL repository to sources list
  apt_repository:
    repo: "{{ MYSQL_8_4_REPO }}"
    state: present

# Installing mysql-8.4-client, mysql-8.4-community-server
# and mysql-8.4-server in separate tasks to resolve dependencies
- name: install mysql-8.4-client
  apt:
    name: "{{ mysql_client_8_4_pkg }}"
    state: present
    update_cache: yes

- name: install mysql-8.4-community-server
  apt:
    name: "{{ mysql_community_server_8_4_pkg }}"
    state: present
    update_cache: yes

- name: install mysql-8.4-server
  apt:
    name: "{{ mysql_server_8_4_pkg }}"
    state: present
    update_cache: yes

- name: restart mysql
  command: service mysql restart

- name: Ensure Anonymous user(s) does not exist
  mysql_user:
    name: ''
    host: "{{ item }}"
    state: absent
    login_unix_socket: "{{ mysql_8_4_socket }}"
  with_items:
    - localhost
    - "{{ ansible_hostname }}"

- name: Alter user root to use caching_sha2_password
  shell:
    mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH caching_sha2_password; SET PASSWORD='';"
  become: true

- name: Post MySQL installation configuration
  include_tasks: configure.yml
- include_tasks: databases.yml
- include_tasks: users.yml
