---
# Users are created manually because the mysql-users module in Ansible is still unable to
# create users correctly using the caching_sha2_password authentication plugin.
# As of now (20/06/2024), there is no release with the module fix.
# References
# https://github.com/ansible-collections/community.mysql/issues/621
# https://github.com/ansible-collections/community.mysql/pull/631
- name: Create or update extra users
  shell: |
    mysql -e "CREATE USER IF NOT EXISTS '{{ item.name }}'@'{{ item.host }}' IDENTIFIED BY '{{ item.password }}';"
  when: item.name != None and item.name != ''
  loop: "{{ MYSQL_CONFIG_USERS }}"

- name: Adding users extra config
  mysql_user:
    name: "{{ item.name }}"
    host: "{{ item.host | default(MYSQL_CONFIG_DEFAULT_ALLOWED_HOSTS) }}"
    priv: "{{ item.priv }}"
    state: "{{ item.state | default('present') }}"
    append_privs: "{{ item.append_privs | default('no') }}"
    encrypted: "{{ item.encrypted | default('no') }}"
  when: item.name != None and item.name != ''
  loop: "{{ MYSQL_CONFIG_USERS }}"
