---
driver:
  name: docker
platforms:
  - name: caddy-instance
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /run
      - /tmp
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    groups:
      - caddy_servers
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        caddy_backend_targets:
        - 'localhost:8080'
        # This emulates a bad node: curl: (7) Failed to connect to localhost port 8082 after 0 ms: Connection refused
        - 'localhost:8082'
        # This emulates a host which proxies 8080 and 8082
        caddy_extra_rules: |
          :8081 {
            import https-proxy {{caddy_backend_targets|join(' ')}}
          }

verifier:
  name: ansible
