---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: redis-7-2-instance
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /run
      - /tmp
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    groups:
      - redis_servers
provisioner:
  name: ansible
  inventory:
    all: {}
verifier:
  name: ansible
