---
driver:
  name: docker
platforms:
  - name: mysql-8-4-ubuntu2404
    image: geerlingguy/docker-ubuntu2404-ansible:latest
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /run
      - /tmp
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    groups:
      - mysql_servers
  - name: mysql-8-4-ubuntu2204
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /run
      - /tmp
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    groups:
      - mysql_servers
provisioner:
  name: ansible
  inventory:
    all:
      MYSQL_CONFIG_USERS:
      - name: user
        host: '%'
        password: password
        state: present
        append_privs: no
verifier:
  name: ansible
