---
- name: Ensure azcopy is not installed
  command: azcopy --version
  register: azcopy_version
  ignore_errors: yes

- name: Download the latest version of azcopy v10
  get_url:
    url: https://aka.ms/downloadazcopy-v10-linux
    dest: /tmp/azcopy.tar.gz
    mode: 0755
  when: azcopy_version.rc != 0

- name: Extract the azcopy archive
  unarchive:
    src: /tmp/azcopy.tar.gz
    dest: /tmp
    remote_src: yes
  when: azcopy_version.rc != 0

- name: Find the azcopy file in the extracted directory
  find:
    paths: /tmp
    patterns: 'azcopy_linux_amd64_*, azcopy'
    file_type: any
  register: azcopy_file
  when: azcopy_version.rc != 0

- name: Copy the azcopy file to /tmp/azcopy
  command: "sudo cp -r {{ item.path }} /tmp/azcopy"
  loop: "{{ azcopy_file.files }}"
  loop_control:
    label: "{{ item.path }}"
  when: azcopy_version.rc != 0

- name: Move the azcopy file to the /usr/bin/ directory
  command: "sudo mv /tmp/azcopy/azcopy /usr/bin/"
  when: azcopy_version.rc != 0

- name: Delete azcopy temporary files
  shell: "sudo rm -rf /tmp/azcopy*"
  when: azcopy_version.rc != 0

- name: Upload files to azure storage
  shell: >
   {{ STORAGE_BACKUPS_AZURE_COMMAND }}
  with_items: "{{ STORAGE_BACKUPS_FILES_TO_UPLOAD }}"
