---
- name: Check if azcopy is installed
  ansible.builtin.command: azcopy --version
  register: azcopy_version
  ignore_errors: true

- name: Download and install azcopy
  when: azcopy_version.rc != 0

  block:
    - name: Download the latest version of azcopy v10
      ansible.builtin.get_url:
        url: https://aka.ms/downloadazcopy-v10-linux
        dest: /tmp/azcopy.tar.gz
        mode: "0755"

    - name: Extract the azcopy archive
      ansible.builtin.unarchive:
        src: /tmp/azcopy.tar.gz
        dest: /tmp
        remote_src: true

    - name: Find the azcopy file in the extracted directory
      ansible.builtin.find:
        paths: /tmp
        patterns: azcopy_linux_amd64_*, azcopy
        file_type: any
      register: azcopy_file

    - name: Copy the azcopy file to /tmp/azcopy
      ansible.builtin.command: sudo cp -r {{ item.path }} /tmp/azcopy
      loop: "{{ azcopy_file.files }}"
      loop_control:
        label: "{{ item.path }}"

    - name: Move the azcopy file to the /usr/bin/ directory
      ansible.builtin.command: sudo mv /tmp/azcopy/azcopy /usr/bin/
    - name: Delete azcopy temporary files
      ansible.builtin.shell: sudo rm -rf /tmp/azcopy*
- name: Upload files to azure storage
  ansible.builtin.shell: >
    {{ STORAGE_BACKUPS_AZURE_COMMAND }}
  with_items: "{{ STORAGE_BACKUPS_FILES_TO_UPLOAD }}"
