---
# S3 option
- name: AWS backups
  ansible.builtin.import_tasks:
    file: aws.yml
  when: STORAGE_BACKUPS_TYPE == 'aws'

# Azure option
- name: Azure backups
  ansible.builtin.import_tasks:
    file: azure.yml
  when: STORAGE_BACKUPS_TYPE == 'azure'
