---
# handlers file for meilisearch

- name: "Systemd daemon-reload"
  ansible.builtin.systemd:
    daemon_reload: 'yes'

- name: "Restart meilisearch"
  ansible.builtin.service:
    name: meilisearch
    state: restarted
