---
DOCKER_MONGO_IMAGE: docker.io/mongo:7.0.7

# Bind adress and ports exposed by the docker container.
# We keep the default port and bind address inside the container and instead
# configure the address and port used by the host using the docker port mapping
# feature.
DOCKER_MONGO_BIND_ADDRESS: 0.0.0.0
DOCKER_MONGO_PORT: 27017

# Volume variable used to mount a docker volume directly
# into a block device. This method was the most peformant
# during testing and has the added benefit of keeping the data
# even when deleting the docker volume (the files will stay in
# the disk partition and can be manually mounted using the linux
# mount command).
# DOCKER_MONGO_VOLUME:
#   device: /dev/nvme1n1
#   fstype: xfs
#   size: "50.00 GB"

mongo_extra_conf: ""
