---
- name: Install Dependencies
  become: true
  ansible.builtin.apt:
    name:
      - python3-debian
      - python3-requests
    update_cache: true
    state: present

- name: Add Docker Engine Repository
  become: true
  ansible.builtin.deb822_repository:
    name: docker
    types: deb
    uris: "{{ DOCKER_APT_REPOSITORY_URL }}"
    suites: "{{ ansible_distribution_release }}"
    components: stable
    architectures: amd64
    signed_by: "{{ DOCKER_GPG_KEY_URL }}"

- name: Install Docker Engine
  become: true
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    update_cache: true
    state: present

- name: Add the default user to the docker group
  become: true
  ansible.builtin.user:
    name: "{{ DOCKER_DEFAULT_USER }}"
    group: docker

- name: Reset ssh connection to allow user changes to affect ansible user
  ansible.builtin.meta: reset_connection

- name: Configure Docker Daemon
  become: true
  ansible.builtin.template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    mode: preserve
  notify:
    - Restart docker daemon
