---
driver:
  name: docker
scenario:
  test_sequence:
    - destroy
    - syntax
    - create
    - converge
    - idempotence
    - verify
    - destroy
provisioner:
  name: ansible
verifier:
  name: ansible
