---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all

  tasks:
  - name: Verify ClickHouse installation
    uri:
      url: "http://localhost:8123/"
      status_code: 200
      timeout: 1
      return_content: yes
    #register: clickhouse_client
    #shell: |
    #  clickhouse-client --user "default" --password="password" --query "SELECT 1"
