# The user that will perform the MySQL restore operation
MYSQL_RESTORE_USER: "{{ EDXAPP_MYSQL_USER }}"
MYSQL_RESTORE_PASSWORD: "{{ EDXAPP_MYSQL_PASSWORD }}"
# If this is empty, the restore will be applied over the whole MySQL instance
MYSQL_RESTORE_DATABASE: ""

# Backup folders
MYSQL_RESTORE_BACKUP_ROOT: "/var/edunext_tmp/mysql"
MYSQL_RESTORE_BACKUP_DATE: "{{ ansible_date_time.date }}"
MYSQL_RESTORE_BACKUP_LOCATION: "{{ MYSQL_RESTORE_BACKUP_ROOT }}/{{ MYSQL_RESTORE_BACKUP_DATE }}.d"
