---
- name: Get disk information for the path we are checking
  ansible.builtin.shell: df -m "{{ AVAILABLE_STORAGE_PATH_TO_CHECK }}" | awk 'NR==2 {print $2","$3}'
  register: disk_info

- name: Get the space consumed by the checked path
  ansible.builtin.shell: du -sh -m "{{ AVAILABLE_STORAGE_PATH_TO_CHECK }}" | awk '{ print $1 }'
  register: path_consumed_space

- name: Extract values
  ansible.builtin.set_fact:
    disk_size: disk_info.stdout.split(',')[0] | int
    disk_used: disk_info.stdout.split(',')[1] | int
    path_space: path_consumed_space | int

- name: Calculate free storage
  ansible.builtin.set_fact:
    disk_free_after_restore: disk_size - (disk_used + path_space)
    disk_free_required: disk_size * (AVAILABLE_STORAGE_THRESHOLD_PERCENTAGE / 100)
    disk_free_percentage: ((disk_size - (disk_used + path_space)) / disk_size ) * 100

- name: Validate free storage
  ansible.builtin.fail:
    msg: "The expected free space on the disk containing the {{ AVAILABLE_STORAGE_PATH_TO_CHECK }} path is less than {{ AVAILABLE_STORAGE_THRESHOLD_PERCENTAGE }}%.
      Expected free space after restore: {{ disk_free_percentage }}%"
  when: disk_free_after_restore < disk_free_required
