- name: Get disk information
  shell: df -B 1 "{{ AVAILABLE_STORAGE_DISK_TO_CHECK }}" | awk 'NR==2 {print $2","$3}'
  register: disk_info

- name: Extract values
  set_fact:
    disk_size: "{{ disk_info.stdout.split(',')[0] | int }}"
    disk_used: "{{ disk_info.stdout.split(',')[1] | int }}"

- name: Calculate free storage
  set_fact:
    disk_free_after_restore: "{{ disk_size | int - (2 * disk_used | int ) }}"
    disk_free_required: "{{ (disk_size | int * (AVAILABLE_STORAGE_THRESHOLD_PERCENTAGE / 100)) | int }}"
    disk_free_percentage: "{{((disk_size | int - (2 * disk_used | int )) / disk_size | int ) * 100 }}"

- name: Validate free storage
  fail:
    msg: "The expected free space on {{ AVAILABLE_STORAGE_DISK_TO_CHECK }} is less than {{ AVAILABLE_STORAGE_THRESHOLD_PERCENTAGE }}%. Expected free space after restore: {{ disk_free_percentage }}%"
  when: disk_free_after_restore < disk_free_required
