# Override these variables
# to change the base directory
# where edX components installed

COMMON_BASE_DIR: /edx
COMMON_DATA_DIR: "{{ COMMON_BASE_DIR}}/var"
COMMON_APP_DIR: "{{ COMMON_BASE_DIR}}/app"
COMMON_LOG_DIR: "{{ COMMON_DATA_DIR }}/log"

COMMON_BIN_DIR: "{{ COMMON_BASE_DIR }}/bin"
COMMON_CFG_DIR: "{{ COMMON_BASE_DIR }}/etc"

COMMON_PIP_VERBOSITY: ''
COMMON_PYPI_MIRROR_URL: 'https://pypi.python.org/simple'
COMMON_NPM_MIRROR_URL: 'https://registry.npmjs.org'

common_directories:
  - path: "{{ COMMON_DATA_DIR }}"
  - path: "{{ COMMON_APP_DIR }}"
  - path: "{{ COMMON_BIN_DIR }}"
  - path: "{{ COMMON_CFG_DIR }}"
  - path: "{{ COMMON_LOG_DIR }}"
    owner: "{{ common_log_user }}"
    group: "{{ common_log_user }}"
  - path: "/etc/logrotate.d/hourly"
  - path: "/etc/rsyslog.d/50-default.conf"
    state: absent

common_web_user: www-data
common_web_group: www-data
common_log_user: syslog
