---
- name: Launch MySQL check available storage
  ansible.builtin.include_role:
    name: available_storage
  vars:
    AVAILABLE_STORAGE_PATH_TO_CHECK: "{{ MYSQL_CLONE_TARGET_PATH }}"

- name: Backup and restore every single database in the clone list
  ansible.builtin.include_tasks: clone.yml
  loop: "{{ MYSQL_CLONE_DB_LIST }}"
