- name: Launch MySQL check available storage
  include_role:
    name: available_storage
  vars:
    AVAILABLE_STORAGE_DISK_TO_CHECK: "{{ MYSQL_CLONE_TARGET_PATH }}"

- name: Backup and restore every single database in the clone list
  include_tasks: clone.yml
  loop: "{{ MYSQL_CLONE_DB_LIST }}"
