---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: clickhouse-instance
    image: geerlingguy/docker-ubuntu2004-ansible:latest
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /run
      - /tmp
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    groups:
      - clickhouse_servers
provisioner:
  name: ansible
  inventory:
    all:
      CLICKHOUSE_DEFAULT_USER_PASSWORD: password
verifier:
  name: ansible
