---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Verify MySQL installation
    register: mysql
    shell: |
      mysql -u "user" --password=password -e "SELECT 1"
