---
# This HELPER role handles the upload of backup artifacts to different storage systems.
# Generally the following variables:
# - STORAGE_BACKUPS_OPTIONS
# - STORAGE_BACKUPS_FILES_TO_UPLOAD
# should be defined when invoking this role.
# For now, only aws S3 and Azure blob storage are supported.

# For aws S3, the STORAGE_BACKUPS_OPTIONS should look like this:

# STORAGE_BACKUPS_OPTIONS:
#   EXTERNAL_STORAGE_TYPE: "aws"
#   EXTERNAL_STORAGE_OPTIONS:
#     S3_BUCKET_NAME: "s3_bucket_name"
#     S3_BUCKET_PATH: "s3_bucket_path"
#     AWS_ACCESS_KEY_ID: "s3_access_key"
#     AWS_SECRET_ACCESS_KEY: "s3_secret_key"
#     AWS_EXTRA_PARAMS: "some extra awscli parameters"

# For azure blob storage, the STORAGE_BACKUPS_OPTIONS should look like this:

# STORAGE_BACKUPS_OPTIONS:
#   EXTERNAL_STORAGE_TYPE: "azure"
#   EXTERNAL_STORAGE_OPTIONS:
#     AZURE_CONTAINER_NAME: "azure_container_name"
#     AZURE_PATH: "azure_path"
#     AZURE_CONTAINER_SAS_TOKEN: "azure_container_sas_token"
#     AZURE_ACCOUNT_NAME: "azure_account_name"

# To get more information about generating a SAS token for azure blob storage,
# please refer to the following documentation: https://learn.microsoft.com/es-mx/rest/api/storageservices/delegate-access-with-shared-access-signature

STORAGE_BACKUPS_OPTIONS: {}
STORAGE_BACKUPS_FILES_TO_UPLOAD: []
STORAGE_BACKUPS_TYPE: "{{ STORAGE_BACKUPS_OPTIONS.EXTERNAL_STORAGE_TYPE | default('') }}"
STORAGE_BACKUPS_TYPE_OPTIONS: "{{ STORAGE_BACKUPS_OPTIONS.EXTERNAL_STORAGE_OPTIONS | default({}) }}"

# AWS storage options extraction
STORAGE_BACKUPS_S3_BUCKET_NAME: "{{ STORAGE_BACKUPS_TYPE_OPTIONS.S3_BUCKET_NAME | default('SET ME PLEASE') }}"
STORAGE_BACKUPS_S3_BUCKET_PATH: "{{ STORAGE_BACKUPS_TYPE_OPTIONS.S3_BUCKET_PATH | default('') }}"
STORAGE_BACKUPS_AWS_ACCESS_KEY_ID: "{{ STORAGE_BACKUPS_TYPE_OPTIONS.AWS_ACCESS_KEY_ID | default('SET ME PLEASE') }}"
STORAGE_BACKUPS_AWS_SECRET_ACCESS_KEY: "{{ STORAGE_BACKUPS_TYPE_OPTIONS.AWS_SECRET_ACCESS_KEY | default('SET ME PLEASE') }}"
STORAGE_BACKUPS_AWS_EXTRA_PARAMS: "{{ STORAGE_BACKUPS_TYPE_OPTIONS.AWS_EXTRA_PARAMS | default('') }}"

# Azure storage options extraction
STORAGE_BACKUPS_AZURE_CONTAINER_NAME: "{{ STORAGE_BACKUPS_TYPE_OPTIONS.AZURE_CONTAINER_NAME | default('SET ME PLEASE') }}"
STORAGE_BACKUPS_AZURE_PATH: "{{ STORAGE_BACKUPS_TYPE_OPTIONS.AZURE_PATH | default('SET ME PLEASE') }}"
STORAGE_BACKUPS_AZURE_CONTAINER_SAS_TOKEN: "{{ STORAGE_BACKUPS_TYPE_OPTIONS.AZURE_CONTAINER_SAS_TOKEN | default('SET ME PLEASE') }}"
STORAGE_BACKUPS_AZURE_ACCOUNT_NAME: "{{ STORAGE_BACKUPS_TYPE_OPTIONS.AZURE_ACCOUNT_NAME | default('SET ME PLEASE') }}"
STORAGE_BACKUPS_AZURE_REMOTE_DEST: https://{{ STORAGE_BACKUPS_AZURE_ACCOUNT_NAME }}.blob.core.windows.net/{{ STORAGE_BACKUPS_AZURE_CONTAINER_NAME }}/{{ STORAGE_BACKUPS_AZURE_PATH
  }}/{{ item | basename }}
STORAGE_BACKUPS_AZURE_COMMAND: azcopy cp '{{ item }}' '{{ STORAGE_BACKUPS_AZURE_REMOTE_DEST }}?{{ STORAGE_BACKUPS_AZURE_CONTAINER_SAS_TOKEN }}'
