---
# Description: Playbook to launch ClickHouse backups
- name: Launch ClickHouse backups
  hosts: clickhouse_servers
  become: true
  gather_facts: true
  roles:
    - role: clickhouse_backup
      tags:
        - clickhouse_backup