---
# Description: Playbook to launch Mongo backups
- name: Launch backups
  hosts: mongo_servers
  become: true
  gather_facts: true
  roles:
    - role: mongo_backup
      tags:
        - mongo_backup
