---

MONGO_BACKUP_USER: "admin"
MONGO_BACKUP_PASSWORD: "mongo_password"
MONGO_BACKUP_ALL_DATABASES: true
MONGO_BACKUP_DATABASES: "edxapp"
MONGO_BACKUP_ROOT: "/var/edunext_tmp/mongo"
MONGO_BACKUP_DATE: "{{ ansible_date_time.date }}"
MONGO_BACKUP_LOCATION: "{{ MONGO_BACKUP_ROOT }}/{{ MONGO_BACKUP_DATE }}.d"
mongo_artifact_path: "{{ MONGO_BACKUP_ROOT }}"
MONGO_BACKUP_PRE_CLEAN_ROOT: false
MONGO_RESTORE_BACKUP: False

# Mongo backup storage options

MONGO_BACKUP_STORAGE_OPTIONS:
  EXTERNAL_STORAGE_TYPE: "aws"
  EXTERNAL_STORAGE_OPTIONS:
    S3_BUCKET_NAME: "s3_bucket_name"
    S3_BUCKET_PATH: "mongo"
    AWS_ACCESS_KEY_ID: "s3_access_key"
    AWS_SECRET_ACCESS_KEY: "s3_secret_key"
