- name: Upload the backup to a remote storage
  include_role:
    name: available_storage
  vars:
    AVAILABLE_STORAGE_DISK_TO_CHECK: "{{ MYSQL_VOLUMES[0].device }}"

- name: Launch restore MySQL Backup
  include_tasks: restore.yml
  vars:
    MYSQL_BACKUP_FILE: "{{ MYSQL_RESTORE_BACKUP_LOCATION }}/{{ MYSQL_RESTORE_BACKUP_DATE }}_mysql.sql"
    MYSQL_BACKUP_FILE_LOCATION: "{{ MYSQL_RESTORE_BACKUP_LOCATION }}"

- name: Clean artifact path
  file:
    state: absent
    path: "{{ MYSQL_RESTORE_BACKUP_ROOT }}"
