# TODO: Verify that the file is indeed a .gz file
- name: Unzip backup file
  shell: "gzip -d {{ MYSQL_RESTORE_BACKUP_LOCATION }}/{{ MYSQL_RESTORE_BACKUP_DATE }}_mysql.sql.gz"
  args:
    chdir: "{{ MYSQL_RESTORE_BACKUP_LOCATION }}"

- name: Restore database
  shell: >
    mysql -u {{ MYSQL_RESTORE_USER }} -p{{ MYSQL_RESTORE_PASSWORD }}
    {% if MYSQL_RESTORE_DATABASE %}{{ MYSQL_RESTORE_DATABASE }}{% endif %} < {{ MYSQL_RESTORE_BACKUP_LOCATION }}/{{ MYSQL_RESTORE_BACKUP_DATE }}_mysql.sql

- name: Clean artifact path
  file:
    state: absent
    path: "{{ MYSQL_RESTORE_BACKUP_ROOT }}"
