- name: Upload the backup to a remote storage
  include_role:
    name: available_storage
  vars:
    DISK_TO_CHECK: "{{ MYSQL_VOLUMES[0].device }}"

- name: Launch MySQL backup
  include_role:
    name: mysql_backup
  vars:
    MYSQL_RESTORE_BACKUP: True
    MYSQL_BACKUP_ALL_DATABASES: false
    MYSQL_BACKUP_USER: "{{ MYSQL_RESTORE_USER }}"
    MYSQL_BACKUP_PASSWORD: "{{ MYSQL_RESTORE_PASSWORD }}"
    MYSQL_BACKUP_DATABASES: "{{ MYSQL_RESTORE_DATABASE }}"
    MYSQL_BACKUP_ROOT: "{{ MYSQL_RESTORE_BACKUP_ROOT }}"
    MYSQL_BACKUP_DATE: "{{ MYSQL_RESTORE_BACKUP_DATE }}"
    MYSQL_BACKUP_LOCATION: "{{ MYSQL_RESTORE_BACKUP_LOCATION }}"

- name: Launch restore MySQL Backup
  include_tasks: restore.yml
  vars:
    MYSQL_BACKUP_FILE: "{{ MYSQL_RESTORE_BACKUP_LOCATION }}/{{ MYSQL_RESTORE_BACKUP_DATE }}_mysql.sql"
    MYSQL_BACKUP_FILE_LOCATION: "{{ MYSQL_RESTORE_BACKUP_LOCATION }}"

- name: Clean artifact path
  file:
    state: absent
    path: "{{ MYSQL_RESTORE_BACKUP_ROOT }}"
