- name: Unzip backup file
  shell: "gzip -d {{ MYSQL_BACKUP_FILE }}.gz"
  args:
    chdir: "{{ MYSQL_BACKUP_FILE_LOCATION }}"

- name: Restore database
  shell: >
    mysql -u {{ MYSQL_RESTORE_STAGE_USER }} -p{{ MYSQL_RESTORE_STAGE_PASSWORD }}
    {{ MYSQL_RESTORE_STAGE_DATABASE }} < {{ MYSQL_BACKUP_FILE }}
