- name: Unzip backup file
  shell: "gzip -d {{ MYSQL_BACKUP_FILE }}.gz"
  args:
    chdir: "{{ MYSQL_BACKUP_FILE_LOCATION }}"

- name: Restore database
  shell: >
    mysql -u {{ MYSQL_RESTORE_USER }} -p{{ MYSQL_RESTORE_PASSWORD }}
    {% if MYSQL_RESTORE_DATABASE %}{{ MYSQL_RESTORE_DATABASE }}{% endif %} < {{ MYSQL_BACKUP_FILE }}
