---
# Source database configuration
MONGO_RESTORE_USER: "{{ EDXAPP_MONGO_USER }}"
MONGO_RESTORE_PASSWORD: "{{ EDXAPP_MONGO_PASSWORD }}"

# Sets the number of collections being restoren in parallel, shich can be adjusted depending on server performance
MONGO_RESTORE_NUM_PARALLEL_COLLECTIONS: 4

# The variables MONGO_RESTORE_ORIGINAL_DATABASE_NAME and MONGO_RESTORE_TARGET_DATABASE_NAME are used
# to restore a database backup with a name to new database with a different name. Both variables must be
# set to enable this clone behavior. This is based on the Mongo documentation that indicates how to clone
# a database: https://www.mongodb.com/docs/database-tools/mongorestore/#copy-clone-a-database
MONGO_RESTORE_ORIGINAL_DATABASE_NAME: ""
MONGO_RESTORE_TARGET_DATABASE_NAME: ""

# Backup folders
MONGO_RESTORE_BACKUP_ROOT: /var/edunext_tmp/mongo
MONGO_RESTORE_BACKUP_DATE: "{{ ansible_date_time.date }}"
MONGO_RESTORE_BACKUP_LOCATION: "{{ MONGO_RESTORE_BACKUP_ROOT }}/{{ MONGO_RESTORE_BACKUP_DATE }}.d"
