# Source database configuration
MONGO_RESTORE_USER: "{{ EDXAPP_MONGO_USER }}"
MONGO_RESTORE_PASSWORD: "{{ EDXAPP_MONGO_PASSWORD }}"
MONGO_RESTORE_DATABASE: ""

# Backup folders
MONGO_RESTORE_BACKUP_ROOT: "/var/edunext_tmp/mongo"
MONGO_RESTORE_BACKUP_DATE: "{{ ansible_date_time.date }}"
MONGO_RESTORE_BACKUP_LOCATION: "{{ MONGO_RESTORE_BACKUP_ROOT }}/{{ MONGO_RESTORE_BACKUP_DATE }}.d"
