# Source database configuration
MONGO_RESTORE_USER: "{{ EDXAPP_MONGO_USER }}"
MONGO_RESTORE_PASSWORD: "{{ EDXAPP_MONGO_PASSWORD }}"
MONGO_RESTORE_DATABASE: "edxapp"

# Destination database configuration
MONGO_RESTORE_STAGE_USER: "{{ STAGE_EDXAPP_MONGO_USER }}"
MONGO_RESTORE_STAGE_PASSWORD: "{{ STAGE_EDXAPP_MONGO_PASSWORD }}"
MONGO_RESTORE_STAGE_DATABASE: "edxapp_stage"
